### ISSUE TITLE
3.2.2 Seizure Warning

### ISSUE THREAD

**Issue by bl2060** [Vivero/Kerbal-VR#68] opened 2019-01-20 05:58 UTC
Was finally able to run this with the new 3.2.2 release but the graphical glitches were so intense it was nauseating. Please fix this soon, I'd love to see this mod in action!

OS: Windows 10
SteamVR: 1.2.8
GPU: GTX 1080 3gb
CPU: I7-6700k

**Comment by samamstar** [comment] 2019-02-12 00:32
Seems to be duplicate of issue #69 with less detail. Could you describe these glitches further?

**Comment by Vivero** [comment] 2019-06-08 21:26
Can you try it with the latest versions of KSP and KerbalVR? Wondering if this issue is now OBE.

**Comment by Vivero** [comment] 2019-06-08 21:26
Closed until further information provided.

**Closed as completed by Vivero** 2019-06-08 21:26 UTC
Labels: performance
