### ISSUE TITLE
Issues with mod

### ISSUE THREAD

**Issue by f8Sk5z** [Vivero/Kerbal-VR#49] opened 2018-06-05 15:20 UTC
Whenever I start up the game, Kerbal Space Program just lags out. The IVA mode doesn't have the button to go to VR mode, and the lag spreads throughout my desktop. Is it because I have an oculus? Help!

**Comment by Vivero** [comment] 2018-06-05 19:45
No idea... could be anything. Posting the KSP.log here might help

**Comment by f8Sk5z** [comment] 2018-06-06 05:23
Nevermind, fixed by taking openvr file from old version and putting it in the new version. You should attempt to fix that.

Also, my hands in oculus dont appear, so thats annoying. All I can do is look around.

**Comment by Vivero** [comment] 2018-06-13 04:39
> Also, my hands in oculus dont appear, so thats annoying. All I can do is look around.

Seems to be a duplicate of #48

**Closed as completed by Vivero** 2018-06-13 04:39 UTC
Labels: bug, duplicate
