### ISSUE TITLE
Star textures not moving smooth with HMD (Oculus)

### ISSUE THREAD

**Issue by Dartans** [Vivero/Kerbal-VR#52] opened 2018-06-11 01:08 UTC
Stars seem to no update with every frame, same as ground textures when in orbit. Seems to be objects that are rendered at a distance do not update at the same frame rate as local objects. Running on GTX1060 3gb i7 7700 16gb ram

**Comment by Vivero** [comment] 2018-06-13 04:41
Sounds like a duplicate of #46

**Closed as completed by Vivero** 2018-06-13 04:41 UTC
Labels: bug, duplicate
